card_num: test-a3eba8ea6cb8a711 #test-bf68347d0ad75a4c

# Hyperparameters
label_list: ['enemy','down','friend']
label_lock_list: ['enemy','down']

mss: True
conf: 0.45
resolution_x: 1920
pos_factor: 0.2
smooth: 0.7140350877192984
max_lock_dis: 100
max_step_dis: 80

use_pid: True
pidx_kp: 1.2
pidx_kd: 3.51
pidx_ki: 0.0
pidy_kp: 1.22
pidy_kd: 0.12
pidy_ki: 0.0
mouse_button: left
auto_lock_button: x1 # set to true to enable auto lock 
delay: 0.02

save_screenshot: False
visualization: True
speed_test: False
print_button: False





