card_num: test-a3eba8ea6cb8a711 #test-bf68347d0ad75a4c

# Hyperparameters
label_list: ['enemy','down','friend']
label_lock_list: ['enemy','down']

speed_test: False
mss: False
visualization: True
conf: 0.45
resolution_x: 1920
pos_factor: 0.2
smooth: 0.7140350877192984
max_lock_dis: 150
max_step_dis: 80

use_pid: True
use_pid_max_dis: 80
pidx_kp: 1.2
pidx_kd: 3.51
pidx_ki: 0.0
pidy_kp: 1.22
pidy_kd: 0.12
pidy_ki: 0.0
print_button: False
mouse_button: left
auto_lock_button: x2 # set to true to enable auto lock 
delay: 0

save_screenshot: True




